/*^ More Infos about DL
 * 
 * For further infos on DL read https://github.com/studio42gmbh/dl/wiki
 */
assert $env.os ~= ".*Windows.*" : "Needs Windows to work properly but OS is " + $env.os;

require "dl:standard/base.dl";

enum MyEnum { Yes, No, Perhaps }

type MyType extends Object
{
	int x @required;
}

int answer		: 42;
String name		: "Data Language";
double PI		: 3.14;
boolean awake	: true;
MyEnum mood		: Perhaps;

// An exported instance of MyType
MyType data @export { 
	x : $answer;
}