/*^ Meine DL Info
 *
 * Ein comment das auto collapsed wird
 *
 */

require "test2.project.dl";

/**
 * Defines a simple project
 */
final dynamic type Project {
	String		display @required;
	String		description @required;
	UUID		id @required;
}

Project project {
	display : "Project";
	description : "";
	id : "e026f997-4410-403b-a061-286692fdc8ca";
	myProp : 5;
}

Folder local {
	
	
	String display : "Local";
	
	Folder src {
		
		String display : "Sources";
	}
	
	Folder test {
		
		String display : "Test";
	}
}

type Long42 @range(0, 42) extends Long;

Long42 i : 5;